name: fooderlich
description: a social recipe app to keep track of new dishes, and share with friends.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0
  provider: ^6.0.3
  flutter_colorpicker: ^1.0.3
  intl: ^0.18.1
  uuid: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  webview_flutter: ^4.2.4
  url_launcher: ^6.1.5
  shared_preferences: ^2.0.15
  go_router: ^10.1.2
  webview_flutter_wkwebview: ^3.7.4
  webview_flutter_android: ^3.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/food_pics/
    - assets/magazine_pics/
    - assets/sample_data/
    - assets/profile_pics/
    - assets/fooderlich_assets/
